/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-container": "#201f20",
          "secondary": "#adc6ff",
          "outline-variant": "#4a4455",
          "outline": "#958da1",
          "primary-container": "#7c3aed",
          "surface-variant": "#353436",
          "secondary-fixed-dim": "#adc6ff",
          "on-error": "#690005",
          "secondary-fixed": "#d8e2ff",
          "on-tertiary": "#2f3131",
          "surface-container-highest": "#353436",
          "inverse-primary": "#732ee4",
          "surface-container-lowest": "#0e0e0f",
          "tertiary-container": "#656767",
          "surface": "#131314",
          "on-primary": "#3f008e",
          "on-tertiary-container": "#e5e6e6",
          "primary-fixed": "#eaddff",
          "surface-tint": "#d2bbff",
          "on-tertiary-fixed": "#1a1c1c",
          "tertiary": "#c6c6c7",
          "surface-dim": "#131314",
          "surface-bright": "#3a393a",
          "inverse-surface": "#e5e2e3",
          "primary-fixed-dim": "#d2bbff",
          "on-error-container": "#ffdad6",
          "error-container": "#93000a",
          "on-secondary": "#002e6a",
          "on-surface-variant": "#ccc3d8",
          "on-tertiary-fixed-variant": "#454747",
          "on-secondary-fixed": "#001a42",
          "on-primary-fixed": "#25005a",
          "on-primary-container": "#ede0ff",
          "tertiary-fixed": "#e2e2e2",
          "tertiary-fixed-dim": "#c6c6c7",
          "inverse-on-surface": "#313031",
          "secondary-container": "#0566d9",
          "on-background": "#e5e2e3",
          "error": "#ffb4ab",
          "on-primary-fixed-variant": "#5a00c6",
          "surface-container-low": "#1c1b1c",
          "on-secondary-container": "#e6ecff",
          "on-surface": "#e5e2e3",
          "on-secondary-fixed-variant": "#004395",
          "surface-container-high": "#2a2a2b",
          "primary": "#d2bbff",
          "background": "#131314",
          "emerald": "#10b981",
          "amber": "#f59e0b"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "2xl": "1rem",
          "3xl": "1.5rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-lg": "48px",
          "stack-xs": "4px",
          "stack-xl": "80px",
          "stack-md": "24px",
          "margin-desktop": "64px",
          "stack-sm": "12px",
          "margin-mobile": "20px",
          "gutter": "24px",
          "container-max": "1280px"
      },
      "fontFamily": {
          "label-md": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "body-lg": ["Inter"],
          "headline-xl": ["Inter"],
          "headline-md": ["Inter"],
          "headline-lg": ["Inter"],
          "label-sm": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
          "headline-md": ["24px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "700"}],
          "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
